export const ADD_DATA_SET = "ADD_DATA_SET";
export const SET_DATA_SETS = "SET_DATA_SETS";
export const SET_PURE_DATA = "SET_PURE_DATA";
export const SET_LABEL_BY_INDEX = "SET_LABEL_BY_INDEX";
export const SET_NEW_DATA_BY_DATA_SET_INDEX = "SET_NEW_DATA_BY_DATA_SET_INDEX";
export const SET_CHART_TITLE = "SET_CHART_TITLE";
export const SET_COLOR_BY_INDEX = "SET_COLOR_BY_INDEX";