theme: jekyll-theme-slate

title       : Chart Master
local       : "pl-PL"
name        : Chart Master
description : "Prosta, reactowa aplikacja do edycji wykresów"

author:
  name             : Patryk Cholewa i Paweł Zych